[project]
name = "mug-hackathon-submission"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp-agent[google]>=0.2.5",
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "pymongo>=4.7.0",
    "python-dotenv>=1.0.1",
]
